### ISSUE TITLE
AttributeError: 'module' object has no attribute 'variables'

### ISSUE THREAD

**Issue by nicolas-ivanov** [LeavesBreathe/Project_RNN_Enhancement#7]
Hello, Leaves!
When trying to use your enhanced modules on GPU I run into the following error:

```
ubuntu@hostname:~/tensorflow$ ./bazel-bin/tf_seq2seq_chatbot/train
You are using the decoding_enhanced library!
Linear functions enhaned has been imported
Unitary Linear has been imported
Preparing dialog data in /var/lib/tf_seq2seq_chatbot/data
I tensorflow/core/common_runtime/local_device.cc:40] Local device intra op parallelism threads: 32
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:903] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:103] Found device 0 with properties: 
name: GRID K520
major: 3 minor: 0 memoryClockRate (GHz) 0.797
pciBusID 0000:00:03.0
Total memory: 4.00GiB
Free memory: 3.95GiB
...
... lots of various output here
...
I tensorflow/core/common_runtime/gpu/gpu_device.cc:702] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GRID K520, pci bus id: 0000:00:03.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:702] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GRID K520, pci bus id: 0000:00:04.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:702] Creating TensorFlow device (/gpu:2) -> (device: 2, name: GRID K520, pci bus id: 0000:00:05.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:702] Creating TensorFlow device (/gpu:3) -> (device: 3, name: GRID K520, pci bus id: 0000:00:06.0)
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:42] Allocating 3.66GiB bytes.
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:52] GPU 0 memory begins at 0x1208f80000 extends to 0x12f30b6000
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 1.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 2.0KiB
...
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 4.00GiB
I tensorflow/core/common_runtime/direct_session.cc:60] Direct session inter op parallelism threads: 32
Creating 4 layers of 1024 units.
Warning -- you have opted to use enhanced_linear function!@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
...
Warning -- you have opted to use enhanced_linear function!@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Warning -- you have opted to use enhanced_linear function!@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Created model with fresh parameters.
Traceback (most recent call last):
  File "/home/ubuntu/tensorflow/bazel-bin/tf_seq2seq_chatbot/train.runfiles/tf_seq2seq_chatbot/train.py", line 15, in <module>
    tf.app.run()
  File "/home/ubuntu/tensorflow/bazel-bin/tf_seq2seq_chatbot/train.runfiles/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/home/ubuntu/tensorflow/bazel-bin/tf_seq2seq_chatbot/train.runfiles/tf_seq2seq_chatbot/train.py", line 12, in main
    train()
  File "/home/ubuntu/tensorflow/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/train.py", line 26, in train
    model = create_model(sess, forward_only=False)
  File "/home/ubuntu/tensorflow/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/seq2seq_model_utils.py", line 35, in create_model
   *session.run(tf.variables.initialize_all_variables())
AttributeError: 'module' object has no attribute 'variables'
```

Probably there is some bug in `seq2seq_enhanced` or `rnn_cell_enhanced`...
Any ideas how to fix this?

The full code is located [here](https://github.com/nicolas-ivanov/tf_seq2seq_chatbot/tree/enhanced_gogogo). In order to reproduce the error you need to run `train.py` either like this
```
python tf_seq2seq_chatbot/train.py
```
if you are lucky to have a proper gpu configuration already, or the following way if you need to build tensorflow from source:
```
cd tensorflow  # cd to the tensorflow source folder
cp -r ~/tf_seq2seq_chatbot ./  # copy project's code to tensorflow root
bazel build -c opt --config=cuda tf_seq2seq_chatbot:train  # build with gpu-enable option
./bazel-bin/tf_seq2seq_chatbot/train  # run the built code
```

**Comment by LeavesBreathe** [comment]
have you tried the most recent clone?

**Comment by nicolas-ivanov** [comment]
Ok, thank you, I'll check it up!

**Comment by LeavesBreathe** [comment]
okay i'll close this but feel free to re-open if you have the same problem!
